
stages:
    - build
    - quality

jobs:
  include:
    - stage: build
      script:
        - mkdir -p testdir/child/
        - touch testdir/child/file1
        - ls testdir
      cache:
        directories:
          - testdir/

    - stage: quality
      script:
        - ls .
        - ls testdir
        - ls testdir/child
      cache:
        directories:
          - testdir/
